services:
  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    ports:
      - "389:389"
      - "636:636"
    environment:
      LDAP_ORGANISATION: "Example Org"
      LDAP_DOMAIN: "example.com"
      LDAP_ADMIN_PASSWORD: "${LDAP_PASSWORD}"


  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
    ports:
      - "443:443"
    depends_on:
      - ldap

volumes:
  ldap_data:
    driver: local