services:

  database:
      image: postgres:${POSTGRES_VERSION:-16}-alpine
      environment:
        POSTGRES_DB: ${POSTGRES_DB:-app}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
        POSTGRES_USER: ${POSTGRES_USER:-elyas}
      ports:
        - "5432:5432"
      volumes:
        - database_data:/var/lib/postgresql/data

  ldap:
    image: broadinstitute/slapd:2.0
    container_name: ldap
    ports:
      - "389:389"
      - "636:636"
    environment:
      LDAP_DEBUGLEVEL: 256  # More detailed debug logging
      LDAP_ORGANIZATION: "Example Org"
      LDAP_DOMAIN: "example.com"
      LDAP_ROOTPASS: "${LDAP_PASSWORD}"
    volumes:
      - ldap_data:/var/lib/ldap  # Persist LDAP data
      - ./ldap-config:/etc/ldap/slapd.d  # Optional: persistent configuration

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
      # PHPLDAPADMIN_HTTPS: "false"  # Disable HTTPS for local development
      PHPLDAPADMIN_HTTP_PORT: 443
    ports:
      - "443:443"
    depends_on:
      - ldap

volumes:
  ldap_data:
    driver: local
    
  database_data: {}