services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # App classes are automatically registered as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # LDAP service alias
    ldap_service:
        class: Symfony\Component\Ldap\Ldap
        factory: ['Symfony\Component\Ldap\Ldap', 'create']
        arguments:
            - 'ext_ldap'
        calls:
            - method: 'bind'
              arguments:
                - '%env(resolve:LDAP_DN)%'
                - '%env(resolve:LDAP_PASSWORD)%'

    Symfony\Component\Ldap\Ldap:
        alias: ldap_service

    # SidebarExtension service definition
    App\Service\SidebarExtension:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $cache: '@cache.app'

    # SessionListener service definition
    App\EventListener\SessionListener:
        arguments:
            $sidebarExtension: '@App\Service\SidebarExtension'
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 100 }
            
    App\Security\Voter\PermissionVoter:
        tags:
            - { name: security.voter }
        arguments:
            $tokenStorage: '@security.token_storage'
            $authorizationChecker: '@security.authorization_checker'